from pymap_elites_multiobjective.parameters.parameters000 import Parameters as p000
from pymap_elites_multiobjective.parameters.parameters111 import Parameters as p111
from pymap_elites_multiobjective.parameters.parameters119 import Parameters as p119
from pymap_elites_multiobjective.parameters.parameters129 import Parameters as p129
from pymap_elites_multiobjective.parameters.parameters200 import Parameters as p200
from pymap_elites_multiobjective.parameters.parameters211 import Parameters as p211
from pymap_elites_multiobjective.parameters.parameters219 import Parameters as p219
from pymap_elites_multiobjective.parameters.parameters500 import Parameters as p500

